# kintoneカスタマイズ用
version: '3'
services:
  # app-custom:
  #   image: nginx
  #   container_name: app_customize
  #   ports:
  #     - "7770:443"
  #     # - "443:443"
  #   # working_dir: /usr/src/app
  #   working_dir: /app
  #   volumes:
  #     # - ./src/html:/app
  #     - ./app/dist:/app
  #     # - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - /usr/src/app/node_modules # コンテナ内のnode_modulesを使用
  #     - ./docker/nginx/conf.d:/etc/nginx/conf.d
  #     - ./docker/nginx/conf/certs:/etc/nginx/certs
  #   build:
  #     context: .
  #     dockerfile: ./docker/nginx/Dockerfile
  discord:
    image: node:17-slim
    container_name: node_discord
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./app_02:/usr/src/app
      # - ./work:/usr/src/work
      - /usr/src/app/node_modules # コンテナ内のnode_modulesを使用
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
